output_file = "C:/Software/Defold/Resonator/asset/sprites/cat/cat_atlas.png"

target_frame_width = 64
target_frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/idle.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/run.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/dash.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/roll.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/long_roll.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/spin.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/pull.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/push.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/climb_ladder.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/jump.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/double_jump.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/long_double_jump.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/wall_slide.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/ledge_grab_idle.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/ledge_grab.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/fall.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/attack.png"
frame_width = 64
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/attack_2.png"
frame_width = 64
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/attack_special.png"
frame_width = 64
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/jump_attack.png"
frame_width = 64
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/ranged_attack.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/jump_ranged_attack.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/take_damage.png"
frame_width = 32
frame_height = 32

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/CatCharacterAnimations1.1/CatCharacterAnimations1.1/SpriteSheets/death.png"
frame_width = 32
frame_height = 32
