output_file = "C:/Software/Defold/Resonator/asset/sprites/enemy/experiment_z9/zomb_dog.png"

target_frame_width = 160
target_frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ #9/experiment_z9/idle.png"
frame_width = 160
frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ #9/experiment_z9/move.png"
frame_width = 160
frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ #9/experiment_z9/death.png"
frame_width = 160
frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ #9/experiment_z9/eat.png"
frame_width = 160
frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ #9/experiment_z9/attack_1.png"
frame_width = 160
frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ #9/experiment_z9/attack_2.png"
frame_width = 160
frame_height = 112