output_file = "C:/Users/Colin/Documents/code/Resonator/asset/sprites/enemy/zomb_gator/zomb_gator_atlas.png"

target_frame_width = 160
target_frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ/ExperimentZ #8/idle.png"
frame_width = 160
frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ/ExperimentZ #8/walk.png"
frame_width = 160
frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ/ExperimentZ #8/death.png"
frame_width = 160
frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ/ExperimentZ #8/atk_quick.png"
frame_width = 160
frame_height = 112

[[sheets]]
path = "C:/Users/Colin/Documents/assets/sthings_monsters/ExperimentZ/ExperimentZ #8/atk_power.png"
frame_width = 160
frame_height = 112