output_file = "C:/Software/Defold/Resonator/asset/sprites/female_knight/female_knight_atlas.png"

target_frame_width = 96
target_frame_height = 96

[[sheets]]
path = "C:/Users/Colin/Desktop/Assets/female_knight_idle.png"
frame_width = 82
frame_height = 45

[[sheets]]
path = "C:/Users/Colin/Desktop/Assets/female_knight_idle_to_walk.png"
frame_width = 82
frame_height = 45

[[sheets]]
path = "C:/Users/Colin/Desktop/Assets/female_knight_walk.png"
frame_width = 82
frame_height = 45

[[sheets]]
path = "C:/Users/Colin/Desktop/Assets/female_knight_attack.png"
frame_width = 82
frame_height = 45