output_file = "C:/Software/Defold/Resonator/asset/sprites/vfx/vfx_atlas.png"

target_frame_width = 64
target_frame_height = 64

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/ColorCombatSprites/red/r_1.png"
frame_width = 48
frame_height = 64

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/ColorCombatSprites/red/r_2.png"
frame_width = 48
frame_height = 48

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/ColorCombatSprites/red/r_3.png"
frame_width = 48
frame_height = 64

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/ColorCombatSprites/red/r_4.png"
frame_width = 64
frame_height = 64

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/ColorCombatSprites/green/g_1.png"
frame_width = 48
frame_height = 64

[[sheets]]
path = "C:/Users/colin/OneDrive/Desktop/ColorCombatSprites/blue/b_1.png"
frame_width = 48
frame_height = 64